version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: xterm
    versions:
    - 4.10.0
    - 4.9.0
  - dependency-name: fs-extra
    versions:
    - 9.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-modal
    versions:
    - 3.11.2
